import Request, { mockRequest } from '../index'

// 这里的url,调用函数时传入，因为 每个页面的列表数据接口的url都有相似的规律，
// 为了抽取 简化代码，这里只写了一个函数，url调用时才传入
export function getUserList(url, data = {}) {
    return Request.post({
        url,
        data,
    })
}

export function deleteUser(url) {
    return Request.delete({
        url,
    })
}

export function addUser(url, data) {
    return Request.post({
        url,
        data,
    })
}

export function updateUser(url, id, data) {
    return Request.patch({
        url: url + '/' + id,
        data,
    })
}

// --------------------------------------------------------------------------------------------------------------
export function getUserList1(url, data = {}) {
    if (url === '/users/list') {
        return mockRequest.post({
            url: '/post',
            data: {
                list: [
                    {
                        id: 177048913,
                        name: 'MonoMono1',
                        realname: 'Mono1',
                        cellphone: 1234567890,
                        enable: 1,
                        departmentId: 2,
                        roleId: 1,
                        createAt: '2024-04-23T05:31:10.000Z',
                        updateAt: '2024-04-28T07:59:29.000Z',
                    },
                    {
                        id: 9,
                        name: 'lyh',
                        realname: '李银河',
                        cellphone: 17754456666,
                        enable: 1,
                        departmentId: 2,
                        roleId: 3,
                        createAt: '2021-05-02T07:24:12.000Z',
                        updateAt: '2021-08-20T04:07:23.000Z',
                    },
                    {
                        id: 8,
                        name: 'wxb',
                        realname: '王小波',
                        cellphone: 18855556666,
                        enable: 1,
                        departmentId: 2,
                        roleId: 3,
                        createAt: '2021-05-02T07:24:12.000Z',
                        updateAt: '2021-05-02T07:26:20.000Z',
                    },
                    {
                        id: 7,
                        name: 'kobe',
                        realname: 'kobe',
                        cellphone: 16655556666,
                        enable: 1,
                        departmentId: 2,
                        roleId: 3,
                        createAt: '2021-05-02T07:24:12.000Z',
                        updateAt: '2021-05-02T07:26:20.000Z',
                    },
                    {
                        id: 6,
                        name: 'lily',
                        realname: 'lily',
                        cellphone: 13355556666,
                        enable: 1,
                        departmentId: 2,
                        roleId: 3,
                        createAt: '2021-05-02T07:24:12.000Z',
                        updateAt: '2021-05-02T07:26:20.000Z',
                    },
                    {
                        id: 5,
                        name: 'coderdemo',
                        realname: 'demo',
                        cellphone: 17766665555,
                        enable: 1,
                        departmentId: 5,
                        roleId: 4,
                        createAt: '2021-08-23T07:24:12.000Z',
                        updateAt: '2021-08-23T07:24:21.000Z',
                    },
                    {
                        id: 4,
                        name: 'codertest',
                        realname: 'test',
                        cellphone: 16655552222,
                        enable: 1,
                        departmentId: 3,
                        roleId: 3,
                        createAt: '2021-08-23T07:25:02.000Z',
                        updateAt: '2021-08-23T07:25:09.000Z',
                    },
                    {
                        id: 3,
                        name: 'lucy',
                        realname: 'lucy',
                        cellphone: 15566668888,
                        enable: 1,
                        departmentId: 1,
                        roleId: 1,
                        createAt: '2021-01-03T04:01:40.000Z',
                        updateAt: '2021-08-09T16:09:41.000Z',
                    },
                    {
                        id: 2,
                        name: 'lilei',
                        realname: 'lilei2',
                        cellphone: 13322223333,
                        enable: 1,
                        departmentId: 1,
                        roleId: 1,
                        createAt: '2021-01-03T03:34:34.000Z',
                        updateAt: '2021-08-20T03:02:12.000Z',
                    },
                    {
                        id: 1,
                        name: 'coderwhy',
                        realname: 'coderwhy',
                        cellphone: 18812345678,
                        enable: 1,
                        departmentId: 1,
                        roleId: 1,
                        createAt: '2021-01-02T10:20:26.000Z',
                        updateAt: '2021-01-03T04:50:13.000Z',
                    },
                ],
                totalCount: 12,
            },
        })
    }
    if (url === '/department/list') {
        return mockRequest.post({
            url: '/post',
            data: {
                list: [
                    {
                        id: 6652,
                        name: '11',
                        parentId: 6651,
                        createAt: '2024-04-29T03:15:04.000Z',
                        updateAt: '2024-04-29T03:15:04.000Z',
                        leader: '11',
                    },
                    {
                        id: 6651,
                        name: '天使',
                        parentId: 6651,
                        createAt: '2024-04-29T02:44:12.000Z',
                        updateAt: '2024-04-29T03:00:21.000Z',
                        leader: '宙斯',
                    },
                    {
                        id: 6648,
                        name: '蕾蕾',
                        parentId: 6609,
                        createAt: '2024-04-28T06:19:59.000Z',
                        updateAt: '2024-04-28T06:19:59.000Z',
                        leader: 'AA',
                    },
                    {
                        id: 6633,
                        name: '测试部',
                        parentId: 3,
                        createAt: '2024-04-26T07:02:31.000Z',
                        updateAt: '2024-04-26T07:13:55.000Z',
                        leader: 'weg',
                    },
                    {
                        id: 6609,
                        name: '后勤部',
                        parentId: 0,
                        createAt: '2024-04-20T08:05:10.000Z',
                        updateAt: '2024-04-20T08:05:10.000Z',
                        leader: 'lily',
                    },
                    {
                        id: 5,
                        name: '人事部',
                        parentId: 1,
                        createAt: '2021-01-02T10:04:02.000Z',
                        updateAt: '2021-05-02T07:33:08.000Z',
                        leader: 'lily',
                    },
                    {
                        id: 4,
                        name: '客服部',
                        parentId: 2,
                        createAt: '2021-01-02T10:04:02.000Z',
                        updateAt: '2021-08-03T11:14:32.000Z',
                        leader: 'lily',
                    },
                    {
                        id: 3,
                        name: '运营部',
                        parentId: 1,
                        createAt: '2021-01-02T10:03:42.000Z',
                        updateAt: '2021-01-05T08:25:52.000Z',
                        leader: 'lucy',
                    },
                    {
                        id: 2,
                        name: '研发部',
                        parentId: 1,
                        createAt: '2021-01-02T10:03:21.000Z',
                        updateAt: '2021-01-05T08:25:49.000Z',
                        leader: 'lilei',
                    },
                    {
                        id: 1,
                        name: '总裁办',
                        parentId: null,
                        createAt: '2021-01-02T10:03:09.000Z',
                        updateAt: '2021-01-05T08:25:46.000Z',
                        leader: 'coderwhy',
                    },
                    {
                        id: 0,
                        name: '鸡你太美🐔',
                        parentId: 1,
                        createAt: '2024-02-01T07:12:41.000Z',
                        updateAt: '2024-02-01T07:16:57.000Z',
                        leader: '鸡你太美🐟',
                    },
                ],
                totalCount: 11,
            },
        })
    }
    if (url === '/role/list') {
        return mockRequest.post({
            url: '/post',
            data: {
                list: [
                    {
                        id: 13317,
                        name: '开发',
                        intro: '前端开发',
                        createAt: '2024-04-17T05:43:29.000Z',
                        updateAt: '2024-04-22T07:30:51.000Z',
                        menuList: [],
                    },
                    {
                        id: 4,
                        name: '人事',
                        intro: '人事管理',
                        createAt: '2021-01-05T11:47:42.000Z',
                        updateAt: '2021-01-05T11:50:11.000Z',
                        menuList: [
                            {
                                id: 38,
                                name: '系统总览',
                                type: 1,
                                url: '/main/analysis',
                                icon: 'el-icon-monitor',
                                sort: 1,
                                children: [
                                    {
                                        id: 39,
                                        url: '/main/analysis/overview',
                                        name: '核心技术',
                                        sort: 106,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                    {
                                        id: 40,
                                        url: '/main/analysis/dashboard',
                                        name: '商品统计',
                                        sort: 107,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        id: 3,
                        name: '运营',
                        intro: '日常事务',
                        createAt: '2021-01-05T11:47:42.000Z',
                        updateAt: '2021-01-05T11:50:11.000Z',
                        menuList: [
                            {
                                id: 38,
                                name: '系统总览',
                                type: 1,
                                url: '/main/analysis',
                                icon: 'el-icon-monitor',
                                sort: 1,
                                children: [
                                    {
                                        id: 39,
                                        url: '/main/analysis/overview',
                                        name: '核心技术',
                                        sort: 106,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                    {
                                        id: 40,
                                        url: '/main/analysis/dashboard',
                                        name: '商品统计',
                                        sort: 107,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                ],
                            },
                            {
                                id: 1,
                                name: '系统管理',
                                type: 1,
                                url: '/main/system',
                                icon: 'el-icon-setting',
                                sort: 2,
                                children: [
                                    {
                                        id: 2,
                                        url: '/main/system/user',
                                        name: '用户管理',
                                        sort: 100,
                                        type: 2,
                                        children: [
                                            {
                                                id: 5,
                                                url: null,
                                                name: '创建用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:create',
                                            },
                                            {
                                                id: 6,
                                                url: null,
                                                name: '删除用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:delete',
                                            },
                                            {
                                                id: 7,
                                                url: null,
                                                name: '修改用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:update',
                                            },
                                            {
                                                id: 8,
                                                url: null,
                                                name: '查询用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 3,
                                        url: '/main/system/department',
                                        name: '部门管理',
                                        sort: 101,
                                        type: 2,
                                        children: [
                                            {
                                                id: 17,
                                                url: null,
                                                name: '创建部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:create',
                                            },
                                            {
                                                id: 18,
                                                url: null,
                                                name: '删除部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:delete',
                                            },
                                            {
                                                id: 19,
                                                url: null,
                                                name: '修改部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:update',
                                            },
                                            {
                                                id: 20,
                                                url: null,
                                                name: '查询部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 4,
                                        url: '/main/system/menu',
                                        name: '菜单管理',
                                        sort: 103,
                                        type: 2,
                                        children: [
                                            {
                                                id: 21,
                                                url: null,
                                                name: '创建菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:create',
                                            },
                                            {
                                                id: 22,
                                                url: null,
                                                name: '删除菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:delete',
                                            },
                                            {
                                                id: 23,
                                                url: null,
                                                name: '修改菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:update',
                                            },
                                            {
                                                id: 24,
                                                url: null,
                                                name: '查询菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 25,
                                        url: '/main/system/role',
                                        name: '角色管理',
                                        sort: 102,
                                        type: 2,
                                        children: [
                                            {
                                                id: 26,
                                                url: null,
                                                name: '创建角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:create',
                                            },
                                            {
                                                id: 27,
                                                url: null,
                                                name: '删除角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:delete',
                                            },
                                            {
                                                id: 28,
                                                url: null,
                                                name: '修改角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:update',
                                            },
                                            {
                                                id: 29,
                                                url: null,
                                                name: '查询角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                ],
                            },
                            {
                                id: 9,
                                name: '商品中心',
                                type: 1,
                                url: '/main/product',
                                icon: 'el-icon-goods',
                                sort: 3,
                                children: [
                                    {
                                        id: 15,
                                        url: '/main/product/category',
                                        name: '商品类别',
                                        sort: 104,
                                        type: 2,
                                        children: [
                                            {
                                                id: 30,
                                                url: null,
                                                name: '创建类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:create',
                                            },
                                            {
                                                id: 31,
                                                url: null,
                                                name: '删除类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:delete',
                                            },
                                            {
                                                id: 32,
                                                url: null,
                                                name: '修改类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:update',
                                            },
                                            {
                                                id: 33,
                                                url: null,
                                                name: '查询类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:query',
                                            },
                                        ],
                                        parentId: 9,
                                    },
                                    {
                                        id: 16,
                                        url: '/main/product/goods',
                                        name: '商品信息',
                                        sort: 105,
                                        type: 2,
                                        children: [
                                            {
                                                id: 34,
                                                url: null,
                                                name: '创建商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:create',
                                            },
                                            {
                                                id: 35,
                                                url: null,
                                                name: '删除商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:delete',
                                            },
                                            {
                                                id: 36,
                                                url: null,
                                                name: '修改商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:update',
                                            },
                                            {
                                                id: 37,
                                                url: null,
                                                name: '查询商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:query',
                                            },
                                        ],
                                        parentId: 9,
                                    },
                                ],
                            },
                            {
                                id: 41,
                                name: '随便聊聊',
                                type: 1,
                                url: '/main/story',
                                icon: 'el-icon-chat-line-round',
                                sort: 4,
                                children: [
                                    {
                                        id: 42,
                                        url: '/main/story/chat',
                                        name: '你的故事',
                                        sort: 108,
                                        type: 2,
                                        children: null,
                                        parentId: 41,
                                    },
                                    {
                                        id: 43,
                                        url: '/main/story/list',
                                        name: '故事列表',
                                        sort: 109,
                                        type: 2,
                                        children: [],
                                        parentId: 41,
                                    },
                                ],
                            },
                        ],
                    },
                    {
                        id: 1,
                        name: '超级管理员',
                        intro: '所有权限',
                        createAt: '2021-01-02T10:01:52.000Z',
                        updateAt: '2021-01-02T10:01:52.000Z',
                        menuList: [
                            {
                                id: 38,
                                name: '系统总览',
                                type: 1,
                                url: '/main/analysis',
                                icon: 'el-icon-monitor',
                                sort: 1,
                                children: [
                                    {
                                        id: 39,
                                        url: '/main/analysis/overview',
                                        name: '核心技术',
                                        sort: 106,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                    {
                                        id: 40,
                                        url: '/main/analysis/dashboard',
                                        name: '商品统计',
                                        sort: 107,
                                        type: 2,
                                        children: null,
                                        parentId: 38,
                                    },
                                ],
                            },
                            {
                                id: 1,
                                name: '系统管理',
                                type: 1,
                                url: '/main/system',
                                icon: 'el-icon-setting',
                                sort: 2,
                                children: [
                                    {
                                        id: 2,
                                        url: '/main/system/user',
                                        name: '用户管理',
                                        sort: 100,
                                        type: 2,
                                        children: [
                                            {
                                                id: 5,
                                                url: null,
                                                name: '创建用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:create',
                                            },
                                            {
                                                id: 6,
                                                url: null,
                                                name: '删除用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:delete',
                                            },
                                            {
                                                id: 7,
                                                url: null,
                                                name: '修改用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:update',
                                            },
                                            {
                                                id: 8,
                                                url: null,
                                                name: '查询用户',
                                                sort: null,
                                                type: 3,
                                                parentId: 2,
                                                permission: 'system:users:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 3,
                                        url: '/main/system/department',
                                        name: '部门管理',
                                        sort: 101,
                                        type: 2,
                                        children: [
                                            {
                                                id: 17,
                                                url: null,
                                                name: '创建部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:create',
                                            },
                                            {
                                                id: 18,
                                                url: null,
                                                name: '删除部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:delete',
                                            },
                                            {
                                                id: 19,
                                                url: null,
                                                name: '修改部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:update',
                                            },
                                            {
                                                id: 20,
                                                url: null,
                                                name: '查询部门',
                                                sort: null,
                                                type: 3,
                                                parentId: 3,
                                                permission: 'system:department:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 4,
                                        url: '/main/system/menu',
                                        name: '菜单管理',
                                        sort: 103,
                                        type: 2,
                                        children: [
                                            {
                                                id: 21,
                                                url: null,
                                                name: '创建菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:create',
                                            },
                                            {
                                                id: 22,
                                                url: null,
                                                name: '删除菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:delete',
                                            },
                                            {
                                                id: 23,
                                                url: null,
                                                name: '修改菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:update',
                                            },
                                            {
                                                id: 24,
                                                url: null,
                                                name: '查询菜单',
                                                sort: null,
                                                type: 3,
                                                parentId: 4,
                                                permission: 'system:menu:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                    {
                                        id: 25,
                                        url: '/main/system/role',
                                        name: '角色管理',
                                        sort: 102,
                                        type: 2,
                                        children: [
                                            {
                                                id: 26,
                                                url: null,
                                                name: '创建角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:create',
                                            },
                                            {
                                                id: 27,
                                                url: null,
                                                name: '删除角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:delete',
                                            },
                                            {
                                                id: 28,
                                                url: null,
                                                name: '修改角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:update',
                                            },
                                            {
                                                id: 29,
                                                url: null,
                                                name: '查询角色',
                                                sort: null,
                                                type: 3,
                                                parentId: 25,
                                                permission: 'system:role:query',
                                            },
                                        ],
                                        parentId: 1,
                                    },
                                ],
                            },
                            {
                                id: 9,
                                name: '商品中心',
                                type: 1,
                                url: '/main/product',
                                icon: 'el-icon-goods',
                                sort: 3,
                                children: [
                                    {
                                        id: 15,
                                        url: '/main/product/category',
                                        name: '商品类别',
                                        sort: 104,
                                        type: 2,
                                        children: [
                                            {
                                                id: 30,
                                                url: null,
                                                name: '创建类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:create',
                                            },
                                            {
                                                id: 31,
                                                url: null,
                                                name: '删除类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:delete',
                                            },
                                            {
                                                id: 32,
                                                url: null,
                                                name: '修改类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:update',
                                            },
                                            {
                                                id: 33,
                                                url: null,
                                                name: '查询类别',
                                                sort: null,
                                                type: 3,
                                                parentId: 15,
                                                permission: 'system:category:query',
                                            },
                                        ],
                                        parentId: 9,
                                    },
                                    {
                                        id: 16,
                                        url: '/main/product/goods',
                                        name: '商品信息',
                                        sort: 105,
                                        type: 2,
                                        children: [
                                            {
                                                id: 34,
                                                url: null,
                                                name: '创建商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:create',
                                            },
                                            {
                                                id: 35,
                                                url: null,
                                                name: '删除商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:delete',
                                            },
                                            {
                                                id: 36,
                                                url: null,
                                                name: '修改商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:update',
                                            },
                                            {
                                                id: 37,
                                                url: null,
                                                name: '查询商品',
                                                sort: null,
                                                type: 3,
                                                parentId: 16,
                                                permission: 'system:goods:query',
                                            },
                                        ],
                                        parentId: 9,
                                    },
                                ],
                            },
                            {
                                id: 41,
                                name: '随便聊聊',
                                type: 1,
                                url: '/main/story',
                                icon: 'el-icon-chat-line-round',
                                sort: 4,
                                children: [
                                    {
                                        id: 42,
                                        url: '/main/story/chat',
                                        name: '你的故事',
                                        sort: 108,
                                        type: 2,
                                        children: null,
                                        parentId: 41,
                                    },
                                    {
                                        id: 43,
                                        url: '/main/story/list',
                                        name: '故事列表',
                                        sort: 109,
                                        type: 2,
                                        children: [],
                                        parentId: 41,
                                    },
                                ],
                            },
                        ],
                    },
                ],
                totalCount: 25,
            },
        })
    }
    if (url === '/menu/list') {
        return mockRequest.post({
            url: '/post',
            data: {
                list: [
                    {
                        id: 38,
                        name: '系统总览',
                        type: 1,
                        url: '/main/analysis',
                        icon: 'el-icon-monitor',
                        sort: 1,
                        createAt: '2021-04-19T14:11:02.000Z',
                        updateAt: '2021-08-20T06:59:55.000Z',
                        children: [
                            {
                                id: 39,
                                url: '/main/analysis/overview',
                                name: '核心技术',
                                sort: 106,
                                type: 2,
                                children: null,
                                createAt: '2021-01-02 18:09:11.000000',
                                parentId: 38,
                                updateAt: '2021-08-19 15:54:41.000000',
                            },
                            {
                                id: 40,
                                url: '/main/analysis/dashboard',
                                name: '商品统计',
                                sort: 107,
                                type: 2,
                                children: null,
                                createAt: '2021-01-02 18:09:22.000000',
                                parentId: 38,
                                updateAt: '2021-08-19 15:56:08.000000',
                            },
                        ],
                    },
                    {
                        id: 1,
                        name: '系统管理',
                        type: 1,
                        url: '/main/system',
                        icon: 'el-icon-setting',
                        sort: 2,
                        createAt: '2021-01-02T10:08:14.000Z',
                        updateAt: '2021-08-20T07:00:08.000Z',
                        children: [
                            {
                                id: 2,
                                url: '/main/system/user',
                                name: '用户管理',
                                sort: 100,
                                type: 2,
                                children: [
                                    {
                                        id: 5,
                                        url: null,
                                        name: '创建用户',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 2,
                                        updateAt: '2021-08-19 16:10:06.000000',
                                        permission: 'system:users:create',
                                    },
                                    {
                                        id: 6,
                                        url: null,
                                        name: '删除用户',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 2,
                                        updateAt: '2021-08-19 16:10:21.000000',
                                        permission: 'system:users:delete',
                                    },
                                    {
                                        id: 7,
                                        url: null,
                                        name: '修改用户',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 2,
                                        updateAt: '2021-08-19 16:10:24.000000',
                                        permission: 'system:users:update',
                                    },
                                    {
                                        id: 8,
                                        url: null,
                                        name: '查询用户',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 2,
                                        updateAt: '2021-08-19 16:10:26.000000',
                                        permission: 'system:users:query',
                                    },
                                ],
                                createAt: '2021-01-02 18:08:47.000000',
                                parentId: 1,
                                updateAt: '2021-08-19 15:52:01.000000',
                            },
                            {
                                id: 3,
                                url: '/main/system/department',
                                name: '部门管理',
                                sort: 101,
                                type: 2,
                                children: [
                                    {
                                        id: 17,
                                        url: null,
                                        name: '创建部门',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 3,
                                        updateAt: '2021-04-19 21:59:39.000000',
                                        permission: 'system:department:create',
                                    },
                                    {
                                        id: 18,
                                        url: null,
                                        name: '删除部门',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 3,
                                        updateAt: '2021-04-19 22:05:07.000000',
                                        permission: 'system:department:delete',
                                    },
                                    {
                                        id: 19,
                                        url: null,
                                        name: '修改部门',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 3,
                                        updateAt: '2021-04-19 22:05:11.000000',
                                        permission: 'system:department:update',
                                    },
                                    {
                                        id: 20,
                                        url: null,
                                        name: '查询部门',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 3,
                                        updateAt: '2021-04-19 22:05:14.000000',
                                        permission: 'system:department:query',
                                    },
                                ],
                                createAt: '2021-01-02 18:09:11.000000',
                                parentId: 1,
                                updateAt: '2021-08-19 15:52:04.000000',
                            },
                            {
                                id: 4,
                                url: '/main/system/menu',
                                name: '菜单管理',
                                sort: 103,
                                type: 2,
                                children: [
                                    {
                                        id: 21,
                                        url: null,
                                        name: '创建菜单',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 4,
                                        updateAt: '2021-04-19 21:59:39.000000',
                                        permission: 'system:menu:create',
                                    },
                                    {
                                        id: 22,
                                        url: null,
                                        name: '删除菜单',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 4,
                                        updateAt: '2021-04-19 22:05:18.000000',
                                        permission: 'system:menu:delete',
                                    },
                                    {
                                        id: 23,
                                        url: null,
                                        name: '修改菜单',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 4,
                                        updateAt: '2021-04-19 22:05:21.000000',
                                        permission: 'system:menu:update',
                                    },
                                    {
                                        id: 24,
                                        url: null,
                                        name: '查询菜单',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 4,
                                        updateAt: '2021-04-19 22:05:24.000000',
                                        permission: 'system:menu:query',
                                    },
                                ],
                                createAt: '2021-01-02 18:09:22.000000',
                                parentId: 1,
                                updateAt: '2021-08-19 15:52:07.000000',
                            },
                            {
                                id: 25,
                                url: '/main/system/role',
                                name: '角色管理',
                                sort: 102,
                                type: 2,
                                children: [
                                    {
                                        id: 26,
                                        url: null,
                                        name: '创建角色',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 25,
                                        updateAt: '2021-04-19 21:59:39.000000',
                                        permission: 'system:role:create',
                                    },
                                    {
                                        id: 27,
                                        url: null,
                                        name: '删除角色',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 25,
                                        updateAt: '2021-04-19 21:59:44.000000',
                                        permission: 'system:role:delete',
                                    },
                                    {
                                        id: 28,
                                        url: null,
                                        name: '修改角色',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 25,
                                        updateAt: '2021-04-19 21:59:47.000000',
                                        permission: 'system:role:update',
                                    },
                                    {
                                        id: 29,
                                        url: null,
                                        name: '查询角色',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 25,
                                        updateAt: '2021-04-19 21:59:49.000000',
                                        permission: 'system:role:query',
                                    },
                                ],
                                createAt: '2021-01-02 18:09:22.000000',
                                parentId: 1,
                                updateAt: '2021-08-19 15:52:17.000000',
                            },
                        ],
                    },
                    {
                        id: 9,
                        name: '商品中心',
                        type: 1,
                        url: '/main/product',
                        icon: 'el-icon-goods',
                        sort: 3,
                        createAt: '2021-01-05T12:15:56.000Z',
                        updateAt: '2021-08-20T07:00:25.000Z',
                        children: [
                            {
                                id: 15,
                                url: '/main/product/category',
                                name: '商品类别',
                                sort: 104,
                                type: 2,
                                children: [
                                    {
                                        id: 30,
                                        url: null,
                                        name: '创建类别',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 15,
                                        updateAt: '2021-04-19 21:59:39.000000',
                                        permission: 'system:category:create',
                                    },
                                    {
                                        id: 31,
                                        url: null,
                                        name: '删除类别',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 15,
                                        updateAt: '2021-04-19 21:59:44.000000',
                                        permission: 'system:category:delete',
                                    },
                                    {
                                        id: 32,
                                        url: null,
                                        name: '修改类别',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 15,
                                        updateAt: '2021-04-19 21:59:47.000000',
                                        permission: 'system:category:update',
                                    },
                                    {
                                        id: 33,
                                        url: null,
                                        name: '查询类别',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 15,
                                        updateAt: '2021-04-19 21:59:49.000000',
                                        permission: 'system:category:query',
                                    },
                                ],
                                createAt: '2021-04-19 21:55:11.000000',
                                parentId: 9,
                                updateAt: '2021-08-19 15:52:12.000000',
                            },
                            {
                                id: 16,
                                url: '/main/product/goods',
                                name: '商品信息',
                                sort: 105,
                                type: 2,
                                children: [
                                    {
                                        id: 34,
                                        url: null,
                                        name: '创建商品',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 16,
                                        updateAt: '2021-08-19 17:29:46.000000',
                                        permission: 'system:goods:create',
                                    },
                                    {
                                        id: 35,
                                        url: null,
                                        name: '删除商品',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 16,
                                        updateAt: '2021-08-19 17:29:50.000000',
                                        permission: 'system:goods:delete',
                                    },
                                    {
                                        id: 36,
                                        url: null,
                                        name: '修改商品',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 16,
                                        updateAt: '2021-08-19 17:29:53.000000',
                                        permission: 'system:goods:update',
                                    },
                                    {
                                        id: 37,
                                        url: null,
                                        name: '查询商品',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 16,
                                        updateAt: '2021-08-19 17:30:02.000000',
                                        permission: 'system:goods:query',
                                    },
                                ],
                                createAt: '2021-04-19 21:57:33.000000',
                                parentId: 9,
                                updateAt: '2021-08-19 15:52:14.000000',
                            },
                        ],
                    },
                    {
                        id: 41,
                        name: '随便聊聊',
                        type: 1,
                        url: '/main/story',
                        icon: 'el-icon-chat-line-round',
                        sort: 4,
                        createAt: '2021-04-19T14:11:02.000Z',
                        updateAt: '2021-08-20T07:00:44.000Z',
                        children: [
                            {
                                id: 42,
                                url: '/main/story/chat',
                                name: '你的故事',
                                sort: 108,
                                type: 2,
                                children: null,
                                createAt: '2021-01-02 18:09:11.000000',
                                parentId: 41,
                                updateAt: '2021-08-19 17:29:31.000000',
                            },
                            {
                                id: 43,
                                url: '/main/story/list',
                                name: '故事列表',
                                sort: 109,
                                type: 2,
                                children: [
                                    {
                                        id: 10,
                                        url: null,
                                        name: '删除故事',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 43,
                                        updateAt: '2021-04-19 21:59:44.000000',
                                        permission: 'system:story:delete',
                                    },
                                    {
                                        id: 11,
                                        url: null,
                                        name: '修改故事',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 43,
                                        updateAt: '2021-04-19 21:59:47.000000',
                                        permission: 'system:story:update',
                                    },
                                    {
                                        id: 12,
                                        url: null,
                                        name: '查询故事',
                                        sort: null,
                                        type: 3,
                                        createAt: '2021-01-03 13:41:01.000000',
                                        parentId: 43,
                                        updateAt: '2021-04-19 21:59:49.000000',
                                        permission: 'system:story:query',
                                    },
                                ],
                                createAt: '2021-01-02 18:09:11.000000',
                                parentId: 41,
                                updateAt: '2021-08-19 15:52:29.000000',
                            },
                        ],
                    },
                ],
            },
        })
    }
    if (url === '/goods/list') {
        return mockRequest.post({
            url: '/post',
            data: {
                list: [
                    {
                        id: 202,
                        name: 'POLO衫女款',
                        oldPrice: '100',
                        newPrice: '88',
                        desc: '春夏可穿',
                        status: 1,
                        imgUrl: 'https://img14.360buyimg.com/n7/jfs/t1/107893/33/47100/72978/65f7d577F0624c53d/c18904df447e5903.jpg',
                        inventoryCount: 1000,
                        saleCount: 1860,
                        favorCount: 1200,
                        address: '兰州',
                        categoryId: 9,
                        createAt: '2024-04-25T14:05:04.000Z',
                        updateAt: '2024-04-29T01:41:59.000Z',
                    },
                    {
                        id: 201,
                        name: 'POLO衫',
                        oldPrice: '100',
                        newPrice: '88',
                        desc: '春夏可穿',
                        status: 1,
                        imgUrl: 'https://imgservice.suning.cn/uimg1/b2c/image/6vye9wpgePu2vuLsndUcaw.jpg_800w_800h_4e',
                        inventoryCount: 3000,
                        saleCount: 1050,
                        favorCount: 888,
                        address: '北京',
                        categoryId: 9,
                        createAt: '2024-04-25T13:59:51.000Z',
                        updateAt: '2024-04-25T14:02:19.000Z',
                    },
                    {
                        id: 183,
                        name: '吊带背心女夏2018秋季新款内搭吊带衫短款性感修身针织打底衫上衣显瘦',
                        oldPrice: '43',
                        newPrice: '30',
                        desc: '吊带背心女夏2018秋季新款内搭吊带衫短款性感修身针织打底衫上衣显瘦',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/17f85e/180927_5i77e04lhaalbg3dai0j4588lbahh_640x960.jpg_560x999.jpg',
                        inventoryCount: 6285,
                        saleCount: 2,
                        favorCount: 3,
                        address: '天津',
                        categoryId: 6,
                        createAt: '2021-04-30T13:43:16.000Z',
                        updateAt: '2021-04-30T13:43:16.000Z',
                    },
                    {
                        id: 174,
                        name: '2018秋季新款时尚套装蝴蝶结波点衬衫圆领麻花毛衣无袖马甲百褶半身裙中长款A字裙套装三件套',
                        oldPrice: '86',
                        newPrice: '60',
                        desc: '2018秋季新款时尚套装蝴蝶结波点衬衫圆领麻花毛衣无袖马甲百褶半身裙中长款A字裙套装三件套',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/c45406/180131_1kgh02j1j4lbb74g0427ljk976612_640x960.jpg_560x999.jpg',
                        inventoryCount: 4118,
                        saleCount: 1356,
                        favorCount: 311,
                        address: '青岛',
                        categoryId: 8,
                        createAt: '2021-04-30T13:42:55.000Z',
                        updateAt: '2021-04-30T13:42:55.000Z',
                    },
                    {
                        id: 173,
                        name: '时尚套装韩版气质甜美镂空灯笼袖针织衫百搭显瘦毛衣女2018秋季新款连衣裙套装',
                        oldPrice: '70',
                        newPrice: '70',
                        desc: '时尚套装韩版气质甜美镂空灯笼袖针织衫百搭显瘦毛衣女2018秋季新款连衣裙套装',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/c45406/180822_5bl46cl4g934133a6cbhkk8l37hl0_640x960.jpg_560x999.jpg',
                        inventoryCount: 1615,
                        saleCount: 1360,
                        favorCount: 286,
                        address: '沈阳',
                        categoryId: 3,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                    {
                        id: 171,
                        name: '2018秋冬新款时尚韩范百搭显瘦背带裤套装灯芯绒裤子+毛衣两件套女',
                        oldPrice: '99',
                        newPrice: '69',
                        desc: '2018秋冬新款时尚韩范百搭显瘦背带裤套装灯芯绒裤子+毛衣两件套女',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/55cf19/180831_3lccd4912aec0lb8fga9ji7ah6bkd_640x960.jpg_560x999.jpg',
                        inventoryCount: 4339,
                        saleCount: 1382,
                        favorCount: 55,
                        address: '南京',
                        categoryId: 8,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                    {
                        id: 170,
                        name: '2018秋装套装新款韩版百搭显瘦长袖条纹雪纺衬衫女宽松直筒背带裤套装两件套',
                        oldPrice: '84',
                        newPrice: '59',
                        desc: '2018秋装套装新款韩版百搭显瘦长袖条纹雪纺衬衫女宽松直筒背带裤套装两件套',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/c45406/180312_5ebi8i8k389leic0g487h3l611kek_640x960.jpg_560x999.jpg',
                        inventoryCount: 7966,
                        saleCount: 1384,
                        favorCount: 80,
                        address: '西安',
                        categoryId: 3,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                    {
                        id: 169,
                        name: '时尚套装两件套网红同款2018秋装女套装新款学生牛仔外套配内搭温柔风小黑裙黑色v领吊带裙潮',
                        oldPrice: '100',
                        newPrice: '70',
                        desc: '时尚套装两件套网红同款2018秋装女套装新款学生牛仔外套配内搭温柔风小黑裙黑色v领吊带裙潮',
                        status: 1,
                        imgUrl: 'http://s3.mogucdn.com/mlcdn/c45406/180819_44ee3hf251agika4lji8958i46e6d_640x960.jpg_560x999.jpg',
                        inventoryCount: 1281,
                        saleCount: 1404,
                        favorCount: 75,
                        address: '青岛',
                        categoryId: 7,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                    {
                        id: 168,
                        name: '连衣裙女新款2018秋款韩版小碎花裙子长袖文艺学生百搭小黑裙',
                        oldPrice: '97',
                        newPrice: '68',
                        desc: '连衣裙女新款2018秋款韩版小碎花裙子长袖文艺学生百搭小黑裙',
                        status: 1,
                        imgUrl: 'http://s11.mogucdn.com/mlcdn/c45406/170402_06ehihjk325cjc7jc4653k1bkek2b_640x960.jpg_560x999.jpg',
                        inventoryCount: 7702,
                        saleCount: 1416,
                        favorCount: 441,
                        address: '西安',
                        categoryId: 5,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                    {
                        id: 167,
                        name: '格姬2018秋装新款两件套圆领灯笼袖连衣裙春装新款韩版名媛大裙摆套装裙时尚套装女6254',
                        oldPrice: '285',
                        newPrice: '199',
                        desc: '格姬2018秋装新款两件套圆领灯笼袖连衣裙春装新款韩版名媛大裙摆套装裙时尚套装女6254',
                        status: 1,
                        imgUrl: 'http://s3.mogucdn.com/mlcdn/c45406/180302_4ji3hab7c3kdhfdg4i0lc86a1287h_640x960.jpg_560x999.jpg',
                        inventoryCount: 2455,
                        saleCount: 1416,
                        favorCount: 62,
                        address: '南京',
                        categoryId: 7,
                        createAt: '2021-04-30T13:42:54.000Z',
                        updateAt: '2021-04-30T13:42:54.000Z',
                    },
                ],
                totalCount: 144,
            },
        })
    }
}
